name: scope_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy>=1.11
  - scipy>=0.19.0
  - matplotlib>=1.5.3
  - astropy>=1.3
  - astroquery>=0.3.7 # from conda-forge channel
  - beautifulsoup4
  - requests
  - anaconda
  - tqdm
  - pandas
  - oktopus # from conda-forge channel
  - bokeh>=1.0 # optional, needed for interact
  - jupyter # optional
  - ipython # optional
  - seaborn # optional
  - photutils # optional, from conda-forge?
  - scikit-learn # optional
  - scikit-image # optional
  - pytest-cov # for documentation and testing
  - pytest-remotedata # for documentation and testing
  - pytest-runner # for documentation and testing
  - sphinx # for documentation and testing
  - sphinx_rtd_theme # for documentation and testing
  - nbsphinx # for documentation and testing
  - numpydoc # for documentation and testing
  - sphinx-automodapi # for documentation and testing
  - graphviz
  - ghp-import
  - pylint
  - celerite
  - flake8
  - lightkurve
  - autopep8
  - pep8
  - pip
  - starry
  - pip:
    - twisted # optional
    - mkl-random # optional
    - fbpca
    - nfft
    - everest-pipeline
